### PR TITLE
fastq down sample from RNAseq data

### PR DESCRIPTION
**Pull request by cflsjt**
Notebook on RNAseq down sample

in directory
/powerplant/workspace/cflsjt/git_repos/PFRAutomatedWorkflows/RNAseq/000.TestData
Contains data and a README.md

If this is ok then add to the repo?

### CODE REVIEW

**Comment by cflsjt** [comment]
@hdzierz I can't request a reviewer or anything

**Comment by mdavy86** [comment]
Another approach would be to use `samtools` and down sample directly from the aligned bam files

```bash
samtools view -q 30 -s [frac] [bamfile]  | samtools fastq ...
```

**Comment by cflsjt** [comment]
These are to get raw fastq though....but yes that would be the easiest way for sure

**Comment by mdavy86** [comment]
It looks to me that using samtools is a better way to generate fastq files than seqtk because the sorted bam file is indexed and the pool size is known so you can filter on flags, mapping quality etc.

**Pull request merged**
